name: 'SimpleCov resultset diff'
description: 'Creates a comment in the pull-request comparing two SimpleCov resultset files.'
author: roque86
inputs:
  base-resultset-path:
    description: 'SimpleCov generated "resultset.json" file path from the base branch'
    required: true
  head-resultset-path:
    description: 'SimpleCov generated "resultset.json" file path from the head branch'
    required: true
  pr-id:
    description: 'Github PR id'
    required: false
  comment-id:
    description: 'Will be used to update a comment instead of creating a new one'
    required: false
  token:
    description: 'Github generated token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
