name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
#  build: # make sure build/ci work properly
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          npm install
#      - run: |
#          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Diff test
        uses: ./
        with:
          base-resultset-path: .github/fixtures/resultset1.json
          head-resultset-path: .github/fixtures/resultset2.json
          pr-id: ${{ steps.pr.outputs.pull_request_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: No diff test
#        uses: ./
#        with:
#          base-resultset-path: .github/fixtures/resultset1.json
#          head-resultset-path: .github/fixtures/resultset1.json
#          token: ${{ secrets.GITHUB_TOKEN }}
